"""Keycloak admin helper for the Selenium walk (#267).

The walk registers its user through the real signup *form*, but the realms have
verifyEmail=true — so Keycloak parks the brand-new account on a "verify your
e-mail" notice and no login is possible. This marks that one disposable user
verified so the walk can carry on, and deletes it at teardown.

It touches nothing else: the account it acts on is the one this run just
created, addressed by its unique per-run e-mail.

It also creates and removes the run's account in the GATE realm (#290): the
environments sit behind an SSO gate, so the browser has to sign in to reach the
signup form at all. That account is disposable and its password is generated by
the caller, so nothing the walk needs has to be a standing secret.

Usage:  kc_admin.py verify <email>
        kc_admin.py delete <email>
        kc_admin.py gate-create <email> <password>
        kc_admin.py gate-delete <email>
"""
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

BASE = os.environ.get("KC_ADMIN_BASE", "http://127.0.0.1:12070").rstrip("/")
REALM = os.environ["KC_REALM"]
USER = os.environ["KC_ADMIN_USERNAME"]
PASS = os.environ["KC_ADMIN_PASSWORD"]
GATE_REALM = os.environ.get("GATE_REALM", "overwatch-gate")
GATE_ROLE = os.environ.get("GATE_ROLE", "internal")


def _call(method, path, token=None, body=None, form=None):
    data, headers = None, {}
    if form is not None:
        data = urllib.parse.urlencode(form).encode()
        headers["Content-Type"] = "application/x-www-form-urlencoded"
    elif body is not None:
        data = json.dumps(body).encode()
        headers["Content-Type"] = "application/json"
    if token:
        headers["Authorization"] = "Bearer " + token
    req = urllib.request.Request(BASE + path, data=data, method=method,
                                 headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            raw = r.read().decode()
            return r.status, (json.loads(raw) if raw.strip() else None)
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode()[:300]


def token():
    st, body = _call("POST", "/auth/realms/master/protocol/openid-connect/token",
                     form={"grant_type": "password", "client_id": "admin-cli",
                           "username": USER, "password": PASS})
    if st != 200:
        sys.exit(f"keycloak admin login failed ({st}) — check KC_ADMIN_* in .env "
                 f"and that {BASE} is reachable (tunnel from the Mac)")
    return body["access_token"]


def find(tok, email, realm=None):
    st, body = _call(
        "GET",
        f"/auth/admin/realms/{realm or REALM}/users"
        f"?email={urllib.parse.quote(email)}&exact=true",
        tok)
    if st != 200 or not body:
        return None
    return body[0]


def gate_create(tok, email, password):
    """A disposable gate account holding the role the gate demands.

    Without the role the login succeeds and the gate still refuses, which is
    the point of having a role at all."""
    u = find(tok, email, GATE_REALM)
    if u:
        _call("DELETE", f"/auth/admin/realms/{GATE_REALM}/users/{u['id']}", tok)
    st, body = _call("POST", f"/auth/admin/realms/{GATE_REALM}/users", tok, {
        "username": email, "email": email, "emailVerified": True,
        "enabled": True, "firstName": "E2E", "lastName": "Gate",
        "credentials": [{"type": "password", "value": password,
                         "temporary": False}]})
    if st not in (201, 409):
        sys.exit(f"could not create the gate account ({st}): {body}")
    u = find(tok, email, GATE_REALM)
    if not u:
        sys.exit(f"gate account {email} not found after creation")
    st, role = _call("GET", f"/auth/admin/realms/{GATE_REALM}/roles/{GATE_ROLE}",
                     tok)
    if st != 200:
        sys.exit(f"realm {GATE_REALM} has no role {GATE_ROLE} ({st}) — is "
                 f"orbit-poc/v2/keycloak-config/overwatch-gate.json applied?")
    st, body = _call("POST",
                     f"/auth/admin/realms/{GATE_REALM}/users/{u['id']}"
                     f"/role-mappings/realm", tok, [role])
    if st != 204:
        sys.exit(f"could not grant {GATE_ROLE} to {email} ({st}): {body}")
    print(f"  gate account ready: {email} ({GATE_ROLE})")


def gate_delete(tok, email):
    u = find(tok, email, GATE_REALM)
    if not u:
        print(f"  teardown: gate account {email} already gone")
        return
    st, _ = _call("DELETE", f"/auth/admin/realms/{GATE_REALM}/users/{u['id']}",
                  tok)
    print(f"  teardown: deleted gate account {email} ({st})")


def main():
    action, email = sys.argv[1], sys.argv[2]
    tok = token()
    if action == "gate-create":
        return gate_create(tok, email, sys.argv[3])
    if action == "gate-delete":
        return gate_delete(tok, email)
    u = find(tok, email)
    if not u:
        if action == "delete":
            print(f"  teardown: {email} already gone")
            return
        sys.exit(f"registration did not create {email} in realm {REALM} — "
                 f"the signup form step failed")
    if action == "verify":
        u["emailVerified"] = True
        u["requiredActions"] = [a for a in u.get("requiredActions", [])
                                if a != "VERIFY_EMAIL"]
        st, _ = _call("PUT", f"/auth/admin/realms/{REALM}/users/{u['id']}", tok, u)
        if st not in (200, 204):
            sys.exit(f"could not verify {email} ({st})")
        print(f"  e-mail marked verified for {email}")
    elif action == "delete":
        st, _ = _call("DELETE", f"/auth/admin/realms/{REALM}/users/{u['id']}", tok)
        print(f"  teardown: deleted {email} ({st})")
    else:
        sys.exit(f"unknown action {action}")


if __name__ == "__main__":
    main()
