#!/usr/bin/env bash
# Automated test run — executes ON the VM. No GitHub Actions needed: this is
# the CI gate (called by `make test`, and by `make stage` before a candidate
# is built) plus a daily systemd timer. Runs both suites in throwaway
# containers and writes TEST_RESULTS.md at the repo root.
#
#   subscription: real Postgres, Keycloak identity monkeypatched at _claims
#   polar:        live Polar API (needs POLAR_ACCESS_TOKEN in orbit-poc/.env)
set -uo pipefail
cd "$(dirname "$0")/.."                       # ~/projects/overwatch on the VM
NET=citest-$$
PG=citest-pg-$$
POLAR_TOKEN=$(grep -h '^POLAR_ACCESS_TOKEN=' orbit-poc/.env 2>/dev/null | cut -d= -f2-)

cleanup(){ podman rm -f "$PG" >/dev/null 2>&1; podman network rm "$NET" >/dev/null 2>&1; }
trap cleanup EXIT

podman network create "$NET" >/dev/null 2>&1 || true
podman run -d --rm --name "$PG" --network "$NET" \
  -e POSTGRES_USER=orbit -e POSTGRES_PASSWORD=orbit -e POSTGRES_DB=orbit \
  docker.io/library/postgres:16 >/dev/null
for _ in $(seq 1 30); do
  podman exec "$PG" pg_isready -U orbit >/dev/null 2>&1 && break; sleep 1; done

# The WHOLE repo goes in, not a hand-picked list of directories. The old cp
# list omitted staging/, .github/ and README.md while the test list named
# suites that read them, so those suites raised collection errors — and a
# collection error aborts the entire run. The gate was executing one skipped
# test and reporting green (#286).
OUT=$(podman run --rm --network "$NET" \
  -e "DB_DSN=dbname=orbit user=orbit password=orbit host=$PG port=5432" \
  -e "POLAR_ACCESS_TOKEN=$POLAR_TOKEN" \
  -e "ORG_DB_SECRET=ci-org-db-secret" \
  -e "OVERWATCH_TEST_DB=1" \
  -v "$PWD:/repo:ro" \
  docker.io/library/python:3.12-slim bash -c '
set -e
mkdir -p /tmp/work
tar -C /repo --exclude=.git --exclude=node_modules -cf - . | tar -C /tmp/work -xf -
cd /tmp/work/orbit-poc
pip install -q -r api/requirements.txt pytest httpx requests >/dev/null 2>&1
apt-get -qq update >/dev/null 2>&1 && apt-get -qq install -y postgresql-client >/dev/null 2>&1
PGPASSWORD=orbit psql -h "$(echo $DB_DSN | sed -E "s/.*host=([^ ]+).*/\1/")" -U orbit -d orbit -f db/init.sql >/dev/null 2>&1
cd api
# Auto-discovery, so a new suite is covered the moment it is written. Every
# exclusion is explicit and carries its reason — the only way to leave a test
# out is to say so here, in the open.
#   test_polar.py  live Polar API, needs POLAR_ACCESS_TOKEN. Polar is the
#                  fallback provider since Creem became the MoR (#269/#270),
#                  so it is run separately and never gates a deploy.
python -m pytest -q -p no:cacheprovider --ignore=test_polar.py 2>&1 | tail -30
echo "MAIN_EXIT=${PIPESTATUS[0]}"
python -m pytest test_polar.py -q -p no:cacheprovider 2>&1 | tail -3
' 2>&1)

# `head -2` closes the pipe early, upstream takes SIGPIPE and — under
# `set -o pipefail` — the whole pipeline reports failure even though it
# matched. `sed -n` reads to EOF, so nothing upstream is ever killed.
SUB=$(echo "$OUT" | grep -oE '[0-9]+ passed|[0-9]+ failed' | sed -n '1,2p' | paste -sd' ' -)
POL=$(echo "$OUT" | grep -oE '[0-9]+ passed|[0-9]+ failed|[0-9]+ skipped' | tail -2 | paste -sd' ' -)
STAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
# pytest's EXIT CODE, not the word "failed" in its summary. A run that dies
# during collection ends "N errors in ...", which contains no "failed" — so
# the old grep scored a suite that never ran as a pass (#286).
MAIN_EXIT=$(echo "$OUT" | sed -n 's/^MAIN_EXIT=//p' | tail -1)
FAILED=${MAIN_EXIT:-1}

cat > TEST_RESULTS.md <<EOF
# Latest test results

Auto-generated by \`deploy/run-tests.sh\` (pre-deploy gate + daily VM timer).
Do not edit by hand.

| Suite | Result | Covers |
|---|---|---|
| subscription | $(echo "$OUT" | grep -oE '[0-9]+ passed.*' | sed -n 1p) | signup, org isolation, service tokens, quotas |
| polar | $(echo "$OUT" | grep -oE '[0-9]+ passed.*' | tail -1) | pro-account product, trial, discount codes |

**Run:** $STAMP · host: VM (podman) · $([ "$FAILED" -eq 0 ] && echo "ALL GREEN ✅" || echo "FAILURES ❌ (pytest exit $FAILED)")

<details><summary>raw</summary>

\`\`\`
$OUT
\`\`\`
</details>
EOF

echo "$OUT"
echo "== wrote TEST_RESULTS.md ($STAMP)"
[ "$FAILED" -eq 0 ]
