#!/usr/bin/env bash
# Automated test run — executes ON the VM. No GitHub Actions needed: this is
# the CI gate (called by `make test`, and by `make stage` before a candidate
# is built) plus a daily systemd timer. Runs both suites in throwaway
# containers and writes TEST_RESULTS.md at the repo root.
#
#   subscription: real Postgres, Keycloak identity monkeypatched at _claims
#   polar:        live Polar API (needs POLAR_ACCESS_TOKEN in orbit-poc/.env)
set -uo pipefail
cd "$(dirname "$0")/.."                       # ~/projects/overwatch on the VM
NET=citest-$$
PG=citest-pg-$$
POLAR_TOKEN=$(grep -h '^POLAR_ACCESS_TOKEN=' orbit-poc/.env 2>/dev/null | cut -d= -f2-)

cleanup(){ podman rm -f "$PG" >/dev/null 2>&1; podman network rm "$NET" >/dev/null 2>&1; }
trap cleanup EXIT

podman network create "$NET" >/dev/null 2>&1 || true
podman run -d --rm --name "$PG" --network "$NET" \
  -e POSTGRES_USER=orbit -e POSTGRES_PASSWORD=orbit -e POSTGRES_DB=orbit \
  docker.io/library/postgres:16 >/dev/null
for _ in $(seq 1 30); do
  podman exec "$PG" pg_isready -U orbit >/dev/null 2>&1 && break; sleep 1; done

OUT=$(podman run --rm --network "$NET" \
  -e "DB_DSN=dbname=orbit user=orbit password=orbit host=$PG port=5432" \
  -e "POLAR_ACCESS_TOKEN=$POLAR_TOKEN" \
  -e "ORG_DB_SECRET=ci-org-db-secret" \
  -v "$PWD/orbit-poc:/src:ro" -v "$PWD/FAQ.md:/faq/FAQ.md:ro" \
  -v "$PWD/deploy/backup.sh:/dr/backup.sh:ro" -v "$PWD/deploy/restore.sh:/dr/restore.sh:ro" \
  -v "$PWD/Makefile:/mk/Makefile:ro" \
  docker.io/library/python:3.12-slim bash -c '
set -e
cd /tmp && cp -r /src/api . && cp -r /src/db . && cp -r /src/web . && cp -r /src/grafana . && cp -r /src/ingest . && cp -r /src/sandbox . && cp /src/docker-compose.selfhost.yml . && cp /faq/FAQ.md . && mkdir -p deploy/caddy && cp /src/deploy/caddy/Caddyfile.selfhost /src/deploy/caddy/Caddyfile.tmpl deploy/caddy/ && cp /dr/backup.sh /dr/restore.sh deploy/ && cp /mk/Makefile .
pip install -q -r api/requirements.txt pytest httpx requests >/dev/null 2>&1
apt-get -qq update >/dev/null 2>&1 && apt-get -qq install -y postgresql-client >/dev/null 2>&1
PGPASSWORD=orbit psql -h "$(echo $DB_DSN | sed -E "s/.*host=([^ ]+).*/\1/")" -U orbit -d orbit -f db/init.sql >/dev/null 2>&1
cd api
python -m pytest test_subscription.py test_rls.py test_frontend.py test_selfhost.py test_faq.py test_backup.py test_fields.py test_dashboards.py test_spacecraft.py test_calibration.py test_metering.py test_billing.py test_sandbox_ports.py test_env_headers.py test_sandbox_deploy.py -q 2>&1 | tail -1
python -m pytest test_polar.py -q 2>&1 | tail -1
' 2>&1)

SUB=$(echo "$OUT" | grep -oE '[0-9]+ passed|[0-9]+ failed' | head -2 | paste -sd' ' -)
POL=$(echo "$OUT" | grep -oE '[0-9]+ passed|[0-9]+ failed|[0-9]+ skipped' | tail -2 | paste -sd' ' -)
STAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
FAILED=$(echo "$OUT" | grep -c "failed")

cat > TEST_RESULTS.md <<EOF
# Latest test results

Auto-generated by \`deploy/run-tests.sh\` (pre-deploy gate + daily VM timer).
Do not edit by hand.

| Suite | Result | Covers |
|---|---|---|
| subscription | $(echo "$OUT" | grep -m1 -oE '[0-9]+ passed.*') | signup, org isolation, service tokens, quotas |
| polar | $(echo "$OUT" | grep -oE '[0-9]+ passed.*' | tail -1) | pro-account product, trial, discount codes |

**Run:** $STAMP · host: VM (podman) · $([ "$FAILED" -eq 0 ] && echo "ALL GREEN ✅" || echo "FAILURES ❌")

<details><summary>raw</summary>

\`\`\`
$OUT
\`\`\`
</details>
EOF

echo "$OUT"
echo "== wrote TEST_RESULTS.md ($STAMP)"
[ "$FAILED" -eq 0 ]
